Updates from jldeen mac dotfiles

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -2,18 +2,19 @@
 #
 # bootstrap installs things.
 
-DOTFILES_ROOT="`pwd`"
+cd "$(dirname "$0")/.."
+DOTFILES_ROOT=$(pwd -P)
 
 set -e
 
 echo ''
 
 info () {
-  printf "  [ \033[00;34m..\033[0m ] $1"
+  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
 }
 
 user () {
-  printf "\r  [ \033[0;33m?\033[0m ] $1 "
+  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
 }
 
 success () {
@@ -26,28 +27,8 @@ fail () {
   exit
 }
 
-install_dependencies () {
-
-  if [ -h /bin/zsh ] || [ -f /bin/zsh ]
-  then
-    if [ ! -d ~/.oh-my-zsh ]
-    then
-      printf "Removing old oh-my-zsh config \n"
-     # rm -rf ~/.oh-my-zsh
-      curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | /bin/zsh
-    fi
-
-  fi
-}
-
-run_install_scripts () {
-
-  source $DOTFILES_ROOT/script/install
-
-}
-
 setup_gitconfig () {
-  if ! [ -f git/gitconfig.symlink ]
+  if ! [ -f git/gitconfig.local.symlink ]
   then
     info 'setup gitconfig'
 
@@ -62,38 +43,36 @@ setup_gitconfig () {
     user ' - What is your github author email?'
     read -e git_authoremail
 
-    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" $DOTFILES_ROOT/git/gitconfig.symlink.example > $DOTFILES_ROOT/git/gitconfig.symlink
+    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
 
     success 'gitconfig'
   fi
 }
 
-link_files () {
-  ln -s $1 $2
-  success "linked $1 to $2"
-}
 
-install_dotfiles () {
-  info 'installing dotfiles'
+link_file () {
+  local src=$1 dst=$2
 
-  overwrite_all=false
-  backup_all=false
-  skip_all=false
+  local overwrite= backup= skip=
+  local action=
 
-  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
-  do
-    dest="$HOME/.`basename \"${source%.*}\"`"
+  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
+  then
 
-    if [ -f $dest ] || [ -d $dest ]
+    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
     then
 
-      overwrite=false
-      backup=false
-      skip=false
+      local currentSrc="$(readlink $dst)"
 
-      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
+      if [ "$currentSrc" == "$src" ]
       then
-        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
+
+        skip=true;
+
+      else
+
+        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
+        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
         read -n 1 action
 
         case "$action" in
@@ -112,36 +91,65 @@ install_dotfiles () {
           * )
             ;;
         esac
+
       fi
 
-      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
-      then
-        rm -rf $dest
-        success "removed $dest"
-      fi
-
-      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
-      then
-        mv $dest $dest\.backup
-        success "moved $dest to $dest.backup"
-      fi
-
-      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
-      then
-        link_files $source $dest
-      else
-        success "skipped $source"
-      fi
-
-    else
-      link_files $source $dest
     fi
 
+    overwrite=${overwrite:-$overwrite_all}
+    backup=${backup:-$backup_all}
+    skip=${skip:-$skip_all}
+
+    if [ "$overwrite" == "true" ]
+    then
+      rm -rf "$dst"
+      success "removed $dst"
+    fi
+
+    if [ "$backup" == "true" ]
+    then
+      mv "$dst" "${dst}.backup"
+      success "moved $dst to ${dst}.backup"
+    fi
+
+    if [ "$skip" == "true" ]
+    then
+      success "skipped $src"
+    fi
+  fi
+
+  if [ "$skip" != "true" ]  # "false" or empty
+  then
+    ln -s "$1" "$2"
+    success "linked $1 to $2"
+  fi
+}
+
+install_dotfiles () {
+  info 'installing dotfiles'
+
+  local overwrite_all=false backup_all=false skip_all=false
+
+  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
+  do
+    dst="$HOME/.$(basename "${src%.*}")"
+    link_file "$src" "$dst"
   done
 }
 
-install_dependencies
-run_install_scripts
+add_cron () {
+  local frequency="*/15 * * * *"
+  local command=$1
+  local job="$frequency $command"
+  cat <(fgrep -i -v "$command" <(crontab -l)) <(echo "$job") | crontab -
+}
+
+add_line () {
+  local command=$1
+  local job="$command"
+  cat <(fgrep -i -v "$command" <(crontab -l)) <(echo "$job") | crontab -
+}
+
 setup_gitconfig
 install_dotfiles
 
@@ -149,13 +157,113 @@ install_dotfiles
 if [ "$(uname -s)" == "Darwin" ]
 then
   info "installing dependencies"
-  if . bin/dot > /tmp/dotfiles-dot 2>&1
+  if source bin/dot | while read -r data; do info "$data"; done
   then
     success "dependencies installed"
+    echo ''
+    echo "Now updating dependencies..."
+    pip3 install --upgrade setuptools
   else
     fail "error installing dependencies"
   fi
 fi
 
 echo ''
-echo '  All installed!'
+info "starting jldeen mods"
+#backup old bin, if exists
+if [ -d $HOME/bin ]
+then
+    echo "current $HOME/bin folder found!!! Creating backup..."
+    sudo mv $HOME/bin bin_old
+    success "backup created"
+else
+    echo "No current $HOME/bin folder found. Proceeding to link bin folder for tumx scripts..."
+fi
+
+# symlink .dotfiles bin to ~
+ln -s $HOME/.dotfiles/bin $HOME/bin && success "symlink for $HOME/bin folder created"
+
+# symlink .dotfiles tmux to ~
+ln -s $HOME/.dotfiles/tmux $HOME/.tmux && success "symlink for $HOME/.tmux folder created"
+
+# symlink VSCode User Settings
+if [ -d $HOME/Library/Application\ Support/Code/User ] ; then 
+  ln -s $HOME/.dotfiles/code/settings.json $HOME/Library/Application\ Support/Code/User/settings.json
+  success "symlink for vs code settings created"
+else
+  info "symlink for vs code settings not created"
+  echo "VS Code does not appear to be installed or has not been launched yet. Cannot create symlink for VS Code User settings..."
+fi
+
+# install Source Code Pro nerd font
+cp $HOME/.dotfiles/Source\ Code\ Pro\ Nerd\ Font\ Complete.ttf /Library/Fonts
+success "Source Code Pro font copied successfully!"
+
+# .config permissions fix
+sudo chown $(whoami) $HOME/.config 
+success '.config permissions fixed'
+
+# airport symlink
+if ! [ -f /usr/local/bin/airport ]
+  then
+    sudo ln -s /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport /usr/local/bin/airport
+    success "symlink for airport created"
+  else 
+    info "symlink for airport already exists"
+  fi
+
+# crontab additions
+add_line "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
+  if [[ $? -eq 0 ]]
+  then
+  success "$PATH added to crontab"
+  else
+  info "ERROR $PATH could not be added to crontab"
+  fi
+
+add_cron "speedtest-cli --simple > ~/bin/bandwidth.log"
+  if [[ $? -eq 0 ]]
+  then
+  success "crontab created for speedtest cli --simple"
+  else
+  info "ERROR crontab could not be created for speedtest cli --simple"
+  fi
+
+add_cron "speedtest-cli --json > ~/bin/bandwidth.json"
+  if [[ $? -eq 0 ]]
+  then
+  success "crontab created for speedtest cli --json"
+  else
+  info "ERROR crontab could not be created for speedtest cli --json"
+  fi
+
+# first run of speedtest-cli
+echo "Running speedtest-cli for tmux status bar data now..."
+speedtest-cli --simple > ~/bin/bandwidth.log
+success "speedtest-cli bandwidth.log created"
+
+speedtest-cli --json > ~/bin/bandwidth.json
+success "speedtest-cli bandwidth.json created"
+
+# iterm2 config
+echo ''
+read -p "Do you currently use iTerm2 and would you like to set jldeen's custom colors? y/n" -n 1 -r
+echo ''
+if [[ $REPLY =~ ^[Yy]$ ]]
+then
+	# Specify the preferences directory
+  defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/.itermcfg/"
+  # Tell iTerm2 to use the custom preferences in the directory
+  defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
+    if [[ $? -eq 0 ]]
+    then
+        success "successfully configured iTerm2 to use jldeen's custom colors..."
+    else
+        fail "failed to apply jldeen's custom colors..." >&2
+fi
+else 
+    echo "You chose not to use iTerm2 or jldeen's custom colors."
+fi
+
+echo ''
+echo '	Badass macOS terminal installed!'
